#!/bin/bash
lein deps

if psql -lqt | cut -d \| -f 1 | grep -q threadstreaks-dev; then
    echo "🌯  DB exists"
else
    echo "🌯  Creating DB"
    createdb threadstreaks-dev
    createdb threadstreaks-test
fi
echo "🌯  DB is good to go"

lein run migrate
