#!/bin/bash
lein deps

if [ ! "$( psql -tAc "SELECT 1 FROM pg_database WHERE datname='threadgambling-dev'" )" = '1' ]; then
    echo "🌯  Creating DB"
    createdb threadgambling-dev
fi
echo "🌯  DB is good to go"
