#!/bin/bash
lein deps

if psql -lqt | cut -d \| -f 1 | grep -q threadgambling-dev; then
    echo "🌯  DB exists"
else
    echo "🌯  Creating DB"
    createdb threadgambling-dev
fi
echo "🌯  DB is good to go"
